### ISSUE TITLE
Doesn't work :)

### ISSUE THREAD

**Issue by stratboy** [mindtwo/post-duplicator-polylang#1]
Hi, thank you for your code. I see it's an old repo, but still I tried it since I've got exactly that problem. But curently the plugin doesn't work. Clears the translations, yes, but then if I try to translate again, the issue will be there again (even with post duplicator disabled). Any idea to solve the problem? I'm a developer, I could do some query on the db eventually. But which one? Did you found the definitive reason of thig bug during last years?

Thank you

**Comment by jonasemde** [comment]
Could you describe in more detail what your problem is? We have tested it and it works as expected.

The plugin should solve the problem that after duplication, there are no Polylang language links to other posts. As I understand it correctly, it works for you too? That's all the plugin is supposed to do.

Could you describe in more detail what does not work after that?
